version: "3"
services:
  emailer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emailer
    ports:
      - "1001:1001"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
