# version: "3"
# services:
#   emailer:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: emailer
#     ports:
#       - "1001:1001"
#     restart: always
#     volumes:
#       - .:/app
#       - /app/node_modules
#     environment:
#         - MONGO_URI=mongodb://127.0.0.1:27017/Emailer
#     env_file:
#       - .env


version: '3'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  emailer:
    build: .
    container_name: emailer
    ports:
      - '1001:1001'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/Emailer

volumes:
  mongo_data:
